### ISSUE TITLE
Android 7.0,打开相机的时候报错误java.lang.SecurityException: Permission Denial: starting Intent

### ISSUE THREAD

**Issue by knjin** [ParkSangGwon/TedBottomPicker#1]
我在TedBottomPicker中#183,查看了打开相机的地方，
Intent cameraInent = new Intent(MediaStore.ACTION_IMAGE_CAPTURE);这里改为
Intent cameraInent = new Intent(MediaStore.ACTION_IMAGE_CAPTURE_SECURE);就能够打开相机了。

参考:
https://developer.android.com/reference/android/provider/MediaStore.html#ACTION_IMAGE_CAPTURE

**Comment by wl386123298** [comment]
android6.x需要加权限判断！

**Comment by ParkSangGwon** [comment]
@knjin 
Do you declare CAMERA permission in Menifest.xml?

**Comment by knjin** [comment]
yes, I declare CAMERA permission in Menifest.xml.

**Comment by ParkSangGwon** [comment]
@knjin 
If we use  `MediaStore.ACTION_IMAGE_CAPTURE` intent, we don't need any permission for capture.
And developer document told us too like this.
(https://developer.android.com/reference/android/provider/MediaStore.html#ACTION_IMAGE_CAPTURE)

But this issue is very strange.

If you use Camera permission in Manifest.xml, you have to request camera permission for `ACTION_IMAGE_CAPTURE`.
Even if you use ``ACTION_IMAGE_CAPTURE` intent , you have to request.
I don't know why we have to request camera permission.


You can check it like this.

1. Don't have CAMERA permission in Manifest.xml
-> you dont need request CAMERA permission for `ACTION_IMAGE_CAPTURE` intent.

2. Have CAMERA permission in Manifest.xml
-> you have to request CAMERA permission for `ACTION_IMAGE_CAPTURE` intent.

**Comment by knjin** [comment]
@ParkSangGwon 
ok ,Thanks your reply.
